name = "limited-licence-chatbot"
main = "src/index.js"
compatibility_date = "2023-11-21"

# Bind the content of the markdown and js files to variables accessible in the worker.
# [[text_blobs]] is used for larger files to ensure they are not truncated.
[[text_blobs]]
binding = "SYSTEM_PROMPT"
path = "limited_licence_chatbot_prompt.md"

[[text_blobs]]
binding = "KNOWLEDGE_BASE"
path = "KnowledgeBase/knowledgeBase.js"

# You can put non-secret variables here if needed
# EXAMPLE_VARIABLE = "some-value" 