name = "limited-licence-chatbot"
main = "src/index.js"
compatibility_date = "2023-11-21"

# No longer needed - files will be imported directly in the worker code.

# You can put non-secret variables here if needed
# EXAMPLE_VARIABLE = "some-value" 